apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-multi-test-tls
spec:
  secretName: k8s-multi-test-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s-multi-test.com
  dnsNames:
    - k8s-multi-test.com
    - www.k8s-multi-test.com
  acme:
    config:
      - http01:
        ingressClass: nginx
        domains:
          - k8s-multi-test.com
          - www.k8s-multi-test.com